---
title: "Matt_Test"
output: html_document
---
```{r}
library(readr)
library(dplyr)
house_prices <- read_csv("data/train.csv") %>%
  group_by(Neighborhood) %>%
  summarise(MeanPrice= mean(SalePrice,na.rm = TRUE)/1000,
            MinPrice = min(SalePrice, na.rm = TRUE)/1000,
            MaxPrice = max(SalePrice, na.rm = TRUE)/1000,
            SdPrice = sd(SalePrice, na.rm = TRUE)/1000) %>%
  arrange(MeanPrice)

library(knitr)
kable((house_prices), caption = "Price by Neighborhood")

library(ggplot2)
library(dplyr)

ggplot(house_prices, aes(x = Neighborhood, y = MeanPrice)) +
  geom_bar(stat = "identity") +
  geom_errorbar(aes(ymin = MeanPrice - SdPrice, ymax = MeanPrice + SdPrice), width = 0.2) +
  labs(title = "Average Sale Price by Neighborhood",
       x = "Neighborhood",
       y = "Average Sale Price / x10^3") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 90))
```

```{r}
library(readr)
library(dplyr)
house_prices <- read_csv("data/train.csv") %>%
  group_by(PavedDrive) %>%
  summarise(MeanPrice= mean(SalePrice,na.rm = TRUE),
            count = n())

cat("Mean Sale Price by Driveway Type")

house_prices
```
```{r}
library(readr)
library(dplyr)
house_prices <- read_csv("data/train.csv") %>%
  group_by(GarageCond) %>%
  summarise(MeanPrice= mean(SalePrice,na.rm = TRUE),
            count = n())

cat("Mean Sale Price by Garage Condition")

house_prices
```
```{r}
library(readr)
library(dplyr)
house_prices <- read_csv("data/train.csv") %>%
      mutate(PoolArea = ifelse(PoolArea > 0, "Has Pool", "No Pool"))%>%
  group_by(PoolArea) %>%
  summarise(MeanPrice= mean(SalePrice,na.rm = TRUE),
            count = n())

cat("Presence of Pool")

house_prices
```
```{r}
library(readr)
library(dplyr)
house_prices <- read_csv("data/train.csv") %>%
      mutate(Fence = ifelse(is.na(Fence), "No fence", "Has fence"))%>%
  group_by(Fence) %>%
  summarise(MeanPrice= mean(SalePrice,na.rm = TRUE),
            count = n())

cat("Presence of Fence")

house_prices
```
```{r}
library(readr)
library(dplyr)
house_prices <- read_csv("data/train.csv") %>%
  group_by(YrSold) %>%
  summarise(MeanPrice= mean(SalePrice,na.rm = TRUE)/1000,
            count = n())

cat("Year Sold")

house_prices

library(ggplot2)
library(dplyr)

ggplot(house_prices, aes(x = YrSold, y = MeanPrice)) +
  geom_bar(stat = "identity") +
  labs(title = "Average Sale Price by Year",
       x = "Year",
       y = "Average Sale Price / x10^3") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 90))
```
```{r}
library(readr)
library(dplyr)
house_prices <- read_csv("data/train.csv") %>%
  group_by(MoSold) %>%
  summarise(MeanPrice= mean(SalePrice,na.rm = TRUE)/1000,
            count = n())

cat("Month Sold")

house_prices

library(ggplot2)
library(dplyr)

ggplot(house_prices, aes(x = MoSold, y = MeanPrice)) +
  geom_bar(stat = "identity") +
  labs(title = "Average Sale Price by Month",
       x = "Month",
       y = "Average Sale Price / x10^3") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 90))
```

